### ISSUE TITLE
[Fix] Script does not allow service to run when the user mistakingly chooses to stake when they do not want to stake

### ISSUE THREAD

**Issue by dagacha** [valory-xyz/trader-quickstart#111]
Release 0.9.4

If the user responds yes to the staking question, but they do not want to stake, the script logic does not currently allow to recover from this wrong initial choice.

`./run_service.sh

---------------
 Trader runner 
---------------

This script will assist you in setting up and running the Trader service (https://github.com/valory-xyz/trader).

Checking the provided RCP...
RPC checks passed.

Detected an existing trader repo. Using this one...
Please stop and manually delete the trader repo if you updated the service's version (v0.9.4)!
You can run the following command, or continue with the pre-existing version of the service:
rm -r trader
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: trader (0.1.0)
[2023-11-18 16:12:11,127][INFO] Performing sync @ /Users/patri/work/demos/0x625CF416a9f525d9480cAFb9B9aC83401a2b2B33/trader-quickstart/trader/packages
[2023-11-18 16:12:11,127][INFO] Checking third party packages.
[2023-11-18 16:12:11,189][INFO] No package was updated.

-----------------------------------------
Checking Autonolas Protocol service state
-----------------------------------------

Ensuring on-chain service 78 is in DEPLOYED state...
Starting staking.py script...

Service 78 is not staked. Checking for available rewards...
Rewards available: 6147528108465965975. Staking the service...
An error occurred while executing staking.py: ('Transaction failed. Receipt:', AttributeDict({'transactionHash': HexBytes('0x733aef8864db9af44d937143fbe449d423698379dad1e1b14fd7005d6966f66e'), 'transactionIndex': 2, 'blockHash': HexBytes('0x01c39f4d4f7e70b4198e0cd0aa0e51105caa7bfede6ee7b3e1258029c168144c'), 'blockNumber': 31013758, 'cumulativeGasUsed': 378375, 'gasUsed': 56207, 'effectiveGasPrice': 17061252992, 'from': '0x22895d6Af70380a25636fb11b1BEEF5c4cf5910C', 'to': '0x5add592ce0a1B5DceCebB5Dcac086Cd9F9e3eA5C', 'contractAddress': None, 'logs': [], 'logsBloom': HexBytes('0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'), 'status': 0, 'error': 'Reverted 0x5c01c068000000000000000000000000ce11e14225575945b8e6dc0d4f2dd4c570f79d9f0000000000000000000000000000000000000000000000000000000000000000', 'type': 2}))
Traceback (most recent call last):
  File "/Users/patri/work/demos/0x625CF416a9f525d9480cAFb9B9aC83401a2b2B33/trader-quickstart/trader/../scripts/staking.py", line 157, in <module>
    send_tx_and_wait_for_receipt(ledger_api, owner_crypto, tx)
  File "/Users/patri/work/demos/0x625CF416a9f525d9480cAFb9B9aC83401a2b2B33/trader-quickstart/scripts/utils.py", line 232, in send_tx_and_wait_for_receipt
    raise ValueError("Transaction failed. Receipt:", receipt)
ValueError: ('Transaction failed. Receipt:', AttributeDict({'transactionHash': HexBytes('0x733aef8864db9af44d937143fbe449d423698379dad1e1b14fd7005d6966f66e'), 'transactionIndex': 2, 'blockHash': HexBytes('0x01c39f4d4f7e70b4198e0cd0aa0e51105caa7bfede6ee7b3e1258029c168144c'), 'blockNumber': 31013758, 'cumulativeGasUsed': 378375, 'gasUsed': 56207, 'effectiveGasPrice': 17061252992, 'from': '0x22895d6Af70380a25636fb11b1BEEF5c4cf5910C', 'to': '0x5add592ce0a1B5DceCebB5Dcac086Cd9F9e3eA5C', 'contractAddress': None, 'logs': [], 'logsBloom': HexBytes('0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'), 'status': 0, 'error': 'Reverted 0x5c01c068000000000000000000000000ce11e14225575945b8e6dc0d4f2dd4c570f79d9f0000000000000000000000000000000000000000000000000000000000000000', 'type': 2}))
`

**Comment by jmoreira-valory** [comment]
Addressed in #117

**Comment by dagacha** [comment]
It doesn't solve the problem in my case, the script is still stuck

`patri@MacBook-Pro-5 trader-quickstart % ./run_service.sh

---------------
 Trader runner 
---------------

This script will assist you in setting up and running the Trader service (https://github.com/valory-xyz/trader.git).

Updated 'AGENT_ID=12' in .trader_runner/.env
Checking the provided RCP...
RPC checks passed.

Detected an existing trader directory. Using this one...
Please stop and manually delete the trader repo if you updated the service's version (v0.9.7)!
You can run the following command, or continue with the pre-existing version of the service:
rm -r trader
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: trader (0.1.0)
[2023-11-20 22:52:26,449][INFO] Performing sync @ /Users/patri/work/demos/0x625CF416a9f525d9480cAFb9B9aC83401a2b2B33/trader-quickstart/trader/packages
[2023-11-20 22:52:26,449][INFO] Checking third party packages.
[2023-11-20 22:52:26,475][INFO] No package was updated.

-----------------------------------------
Checking Autonolas Protocol service state
-----------------------------------------

Ensuring on-chain service 78 is in DEPLOYED state...
Checking balance of owner/operator's address (minimum required 0.0250 DAI):
  - Address: 0x22895d6Af70380a25636fb11b1BEEF5c4cf5910C
  - Balance: 0.2923 DAI
    OK.

[Service owner] Activating registration for on-chain service 78...
Your service is using staking. Therefore, you need to provide a total of 50.0000 OLAS to your owner/operator's address:
    25.0000 OLAS for bonding (service owner)
        +
    25.0000 OLAS for staking (operator).

Checking balance of owner/operator's address (minimum required 50.0000 OLAS):
  - Address: 0x22895d6Af70380a25636fb11b1BEEF5c4cf5910C
  - Balance: 0.0000 OLAS

    Please, fund address 0x22895d6Af70380a25636fb11b1BEEF5c4cf5910C with at least 50.0000 OLAS.
    Waiting... - ^C`

**Comment by dagacha** [comment]
This faulty behaviour is no longer observed.
